---
extends:
  - airbnb
  - 'plugin:jest/recommended'
  - prettier
  - prettier/react

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    - node
    - webpack

rules:
  import/extensions: 0
  react/prop-types: 0
  no-console: 0
